name: fuzzies
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  chat_bubbles: ^1.1.0
  cupertino_icons: ^1.0.2
  animations: ^2.0.2
  yandex_mapkit: ^2.0.1
  equatable: ^2.0.0
  collection: ^1.15.0
  shared_preferences: ^2.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  pedantic: ^1.11.0
  flutter_native_splash: ^1.3.3

flutter:
  assets:
    - lib/assets/
  uses-material-design: true
